### ISSUE TITLE
mainnet explorer crash

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony-dashboard#90]
https://harmonyone.pagerduty.com/incidents/PFGQJMH/

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'serve' ]
2 info using npm@6.13.4
3 info using node@v10.18.0
4 verbose run-script [ 'preserve', 'serve', 'postserve' ]
5 info lifecycle harmony-website@1.0.0~preserve: harmony-website@1.0.0
6 info lifecycle harmony-website@1.0.0~serve: harmony-website@1.0.0
7 verbose lifecycle harmony-website@1.0.0~serve: unsafe-perm in lifecycle true
8 verbose lifecycle harmony-website@1.0.0~serve: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/ec2-user/projects/harmony-dashboard/node_modules/.bin:/sbin:/bin:/usr/sbin:/usr/bin:/bin:/usr/lib/golang/bin
9 verbose lifecycle harmony-website@1.0.0~serve: CWD: /home/ec2-user/projects/harmony-dashboard
10 silly lifecycle harmony-website@1.0.0~serve: Args: [ '-c',
10 silly lifecycle   'http-server -p 2000 dist --ssl --cert $CERT_FILE --key $KEY_FILE' ]
11 silly lifecycle harmony-website@1.0.0~serve: Returned: code: 1  signal: null
12 info lifecycle harmony-website@1.0.0~serve: Failed to exec serve script
13 verbose stack Error: harmony-website@1.0.0 serve: `http-server -p 2000 dist --ssl --cert $CERT_FILE --key $KEY_FILE`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid harmony-website@1.0.0
15 verbose cwd /home/ec2-user/projects/harmony-dashboard
16 verbose Linux 4.14.123-86.109.amzn1.x86_64
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "serve"
18 verbose node v10.18.0
19 verbose npm  v6.13.4
20 error code ELIFECYCLE
21 error errno 1
22 error harmony-website@1.0.0 serve: `http-server -p 2000 dist --ssl --cert $CERT_FILE --key $KEY_FILE`
22 error Exit status 1
23 error Failed at the harmony-website@1.0.0 serve script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by LeoHChen** [comment]
```
[Thu May 14 2020 11:34:18 GMT+0000 (Coordinated Universal Time)] "GET /" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55"
[Thu May 14 2020 11:34:18 GMT+0000 (Coordinated Universal Time)] "GET /" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55"
[Thu May 14 2020 11:34:18 GMT+0000 (Coordinated Universal Time)] "GET /sidekiq" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55"
[Thu May 14 2020 11:34:18 GMT+0000 (Coordinated Universal Time)] "GET /sidekiq" Error (404): "Not found"
[Thu May 14 2020 11:34:18 GMT+0000 (Coordinated Universal Time)] "GET /sidekiq.json" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55"
[Thu May 14 2020 11:34:18 GMT+0000 (Coordinated Universal Time)] "GET /sidekiq.json" Error (404): "Not found"
[Thu May 14 2020 11:34:18 GMT+0000 (Coordinated Universal Time)] "GET /sidekiq%00" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55"
internal/fs/utils.js:453
throw err;
^

TypeError [ERR_INVALID_ARG_VALUE]: The argument 'path' must be a string or Uint8Array without null bytes. Received '/home/ec2-user/projects/harmony-dashboard/dist/sidekiq\u0000'
at Object.stat (fs.js:825:3)
at statFile (/home/ec2-user/projects/harmony-dashboard/node_modules/ecstatic/lib/ecstatic.js:350:10)
at Array.middleware (/home/ec2-user/projects/harmony-dashboard/node_modules/ecstatic/lib/ecstatic.js:460:7)
at dispatch (/home/ec2-user/projects/harmony-dashboard/node_modules/union/lib/routing-stream.js:110:21)
at Object.onceWrapper (events.js:286:20)
at module.exports.emit (events.js:198:13)
at Array.<anonymous> (/home/ec2-user/projects/harmony-dashboard/node_modules/http-server/lib/http-server.js:100:9)
at dispatch (/home/ec2-user/projects/harmony-dashboard/node_modules/union/lib/routing-stream.js:119:21)
at module.exports.RoutingStream.route (/home/ec2-user/projects/harmony-dashboard/node_modules/union/lib/routing-stream.js:121:5)
at Object.onceWrapper (events.js:286:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! harmony-website@1.0.0 serve: `http-server -p 2000 dist --ssl --cert $CERT_FILE --key $KEY_FILE`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the harmony-website@1.0.0 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! /home/ec2-user/.npm/_logs/2020-05-14T11_34_18_627Z-debug.log
```
